export const adminCopy = {
  en: {
    welcome: 'Welcome to your dashboard!',
    nextSteps: "Here's what to do next:",
    seededIntro: ' with a few products and pages to get your project started, then ',
    visitWebsite: 'visit your website',
    seededOutro: ' to see the results.',
    stripeIntro: 'Go to ',
    stripeLink: 'Stripe to get your API keys',
    stripeOutro: '. Create an account if needed, add the keys to your environment variables, and restart the server. See the ',
    readme: 'README',
    readmeOutro: ' for details.',
    modifyIntro: 'Update your ',
    collections: 'collections',
    andAdd: ' and add ',
    fields: 'fields',
    asNeeded: ' as needed. If you are new to Payload, read the ',
    gettingStarted: 'Getting Started',
    docs: ' docs.',
    proTip: 'Tip: This section is a ',
    customComponent: 'custom component',
    removeAnytime: ', and you can remove it by updating ',
    config: 'payload.config',
    configEnd: '.',
    seedButton: 'Seed your database',
    loadingSuffix: ' (seeding...)',
    doneSuffix: ' (done!)',
    errorSuffix: ' (error: {{error}})',
    alreadySeeded: 'Database already seeded.',
    alreadySeeding: 'Seeding is already in progress.',
    seedError: 'An error occurred. Please refresh and try again.',
    seedFailed: 'An error occurred while seeding.',
    seedLoading: 'Seeding with sample data…',
    seedSuccess: 'Database seeded! You can now ',
    loginWelcome: 'Welcome to your dashboard!',
    loginDescription: ' This is where site admins sign in to manage the store. Customers should ',
    customerLogin: 'sign in on the website instead',
    loginOutro: ' to access their account, order history, and more.',
  },
  fa: {
    welcome: 'به پیشخوان خوش آمدید!',
    nextSteps: 'برای شروع این کارها را انجام دهید:',
    seededIntro: ' با چند محصول و صفحهٔ نمونه، کار را شروع کنید و سپس ',
    visitWebsite: 'از وب‌سایت بازدید کنید',
    seededOutro: ' تا نتیجه را ببینید.',
    stripeIntro: 'به ',
    stripeLink: 'Stripe بروید و کلیدهای API را دریافت کنید',
    stripeOutro: '. در صورت نیاز حساب بسازید، کلیدها را در متغیرهای محیطی قرار دهید و سرور را دوباره اجرا کنید. برای جزئیات، ',
    readme: 'README',
    readmeOutro: ' را ببینید.',
    modifyIntro: 'در صورت نیاز ',
    collections: 'مجموعه‌ها',
    andAdd: ' را ویرایش کنید و ',
    fields: 'فیلد',
    asNeeded: ' بیشتری بیفزایید. اگر تازه با Payload آشنا شده‌اید، راهنمای ',
    gettingStarted: 'شروع به کار',
    docs: ' را بخوانید.',
    proTip: 'نکته: این بخش یک ',
    customComponent: 'کامپوننت سفارشی',
    removeAnytime: ' است و می‌توانید با ویرایش فایل ',
    config: 'payload.config',
    configEnd: ' آن را حذف کنید.',
    seedButton: 'افزودن داده‌های نمونه',
    loadingSuffix: ' (در حال افزودن...)',
    doneSuffix: ' (انجام شد)',
    errorSuffix: ' (خطا: {{error}})',
    alreadySeeded: 'داده‌های نمونه قبلاً افزوده شده‌اند.',
    alreadySeeding: 'افزودن داده‌ها در حال انجام است.',
    seedError: 'خطایی رخ داد. صفحه را تازه‌سازی و دوباره تلاش کنید.',
    seedFailed: 'افزودن داده‌های نمونه با خطا روبه‌رو شد.',
    seedLoading: 'در حال افزودن داده‌های نمونه…',
    seedSuccess: 'داده‌های نمونه افزوده شدند. حالا می‌توانید ',
    loginWelcome: 'به پیشخوان خوش آمدید!',
    loginDescription: ' مدیران سایت از اینجا برای مدیریت فروشگاه وارد می‌شوند. مشتریان باید ',
    customerLogin: 'از طریق وب‌سایت وارد شوند',
    loginOutro: ' تا به حساب کاربری، تاریخچهٔ سفارش‌ها و بخش‌های دیگر دسترسی داشته باشند.',
  },
} as const

export type AdminLanguage = keyof typeof adminCopy

export const getAdminCopy = (language: string) =>
  adminCopy[language === 'fa' ? 'fa' : 'en']
